# Generated by Django 3.2.3 on 2021-05-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_city_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openweather_id', models.IntegerField()),
                ('city_name', models.CharField(max_length=255)),
                ('temperature', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'город', 'verbose_name_plural': 'города'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
        migrations.AddField(
            model_name='city',
            name='openweather_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='reminding_time_period',
            field=models.IntegerField(choices=[(0, 'No reminding'), (3600, 'Every 1 hour'), (10800, 'Every 3 hour'), (21600, 'Every 6 hour'), (43200, 'Every 12 hour'), (86400, 'Every 24 hour')], default=0),
        ),
    ]
