# Generated by Django 3.2.3 on 2021-05-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20210528_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='openweather_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
